### ISSUE TITLE
Departure time for each trip

### ISSUE THREAD

**Issue by yululeah** [chintanp/ChargEval#7]
How to determine the departure time of each vehicle for each trip in the trip generation?

**Comment by chintanp** [comment]
The `trip_start_time` is calculated using the function `rnd_date_time()` ([link](https://github.com/chintanp/wsdot_evse_update_states/blob/858fc8956ff884e9b6a1c321efd2c3a2f665d661/R/generate_evtrip_scenarios.R#L14)) such that a vehicle reaches its destination by 10pm.
